[tox]
envlist = py39

[testenv]
deps=-r{toxinidir}/requirements.txt
     -r{toxinidir}/requirements.test.txt
     pytest
     pytest-cov

setenv=FLASK_ENV=testing
commands= pytest --cov-config .coveragerc --cov-report term-missing --cov swagger_server swagger_server/test


[coverage:run]
# Coverage configuration:
# https://coverage.readthedocs.io/en/latest/config.html
omit =
    venv
    swagger_server/test

[tool:pytest]
# pytest configuration:
# https://docs.pytest.org/en/stable/customize.html

# Timeout for tests, so they can not take longer
# than this amount of seconds.
# You should adjust this value to be as low as possible.
# Configuration:
# https://pypi.org/project/pytest-timeout/

# Directories that are not visited by pytest collector:
norecursedirs = *.egg .eggs dist build docs .tox .git __pycache__

testpaths =
    swagger_server/test

# You will need to measure your tests speed with `-n auto` and without it,
# so you can see whether it gives you any performance gain, or just gives
# you an overhead.
addopts =
  # Output:
  --tb=short
  # Parallelism:
  # -n auto
  # --boxed
  # Coverage:
  --cov=monolith
  --cov-branch
  --cov-report=term-missing:skip-covered
  --cov-report=html
  --cov-fail-under=90