# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponseDefault(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, error_message: str=None):  # noqa: E501
        """InlineResponseDefault - a model defined in Swagger

        :param error_message: The error_message of this InlineResponseDefault.  # noqa: E501
        :type error_message: str
        """
        self.swagger_types = {
            'error_message': str
        }

        self.attribute_map = {
            'error_message': 'error_message'
        }
        self._error_message = error_message

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponseDefault':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_default of this InlineResponseDefault.  # noqa: E501
        :rtype: InlineResponseDefault
        """
        return util.deserialize_model(dikt, cls)

    @property
    def error_message(self) -> str:
        """Gets the error_message of this InlineResponseDefault.


        :return: The error_message of this InlineResponseDefault.
        :rtype: str
        """
        return self._error_message

    @error_message.setter
    def error_message(self, error_message: str):
        """Sets the error_message of this InlineResponseDefault.


        :param error_message: The error_message of this InlineResponseDefault.
        :type error_message: str
        """

        self._error_message = error_message
