# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.user import User  # noqa: F401,E501
from swagger_server import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, authentication: str='failure', user: User=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger

        :param authentication: The authentication of this InlineResponse200.  # noqa: E501
        :type authentication: str
        :param user: The user of this InlineResponse200.  # noqa: E501
        :type user: User
        """
        self.swagger_types = {
            'authentication': str,
            'user': User
        }

        self.attribute_map = {
            'authentication': 'authentication',
            'user': 'user'
        }
        self._authentication = authentication
        self._user = user

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def authentication(self) -> str:
        """Gets the authentication of this InlineResponse200.

        It can be failure or success  # noqa: E501

        :return: The authentication of this InlineResponse200.
        :rtype: str
        """
        return self._authentication

    @authentication.setter
    def authentication(self, authentication: str):
        """Sets the authentication of this InlineResponse200.

        It can be failure or success  # noqa: E501

        :param authentication: The authentication of this InlineResponse200.
        :type authentication: str
        """

        self._authentication = authentication

    @property
    def user(self) -> User:
        """Gets the user of this InlineResponse200.


        :return: The user of this InlineResponse200.
        :rtype: User
        """
        return self._user

    @user.setter
    def user(self, user: User):
        """Sets the user of this InlineResponse200.


        :param user: The user of this InlineResponse200.
        :type user: User
        """

        self._user = user
