# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse400(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, authentication: str='failure'):  # noqa: E501
        """InlineResponse400 - a model defined in Swagger

        :param authentication: The authentication of this InlineResponse400.  # noqa: E501
        :type authentication: str
        """
        self.swagger_types = {
            'authentication': str
        }

        self.attribute_map = {
            'authentication': 'authentication'
        }
        self._authentication = authentication

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse400':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_400 of this InlineResponse400.  # noqa: E501
        :rtype: InlineResponse400
        """
        return util.deserialize_model(dikt, cls)

    @property
    def authentication(self) -> str:
        """Gets the authentication of this InlineResponse400.

        It can be failure or success  # noqa: E501

        :return: The authentication of this InlineResponse400.
        :rtype: str
        """
        return self._authentication

    @authentication.setter
    def authentication(self, authentication: str):
        """Sets the authentication of this InlineResponse400.

        It can be failure or success  # noqa: E501

        :param authentication: The authentication of this InlineResponse400.
        :type authentication: str
        """

        self._authentication = authentication
