"""empty message

Revision ID: 2a03d5026d0d
Revises: 8e1840b6cee8
Create Date: 2021-12-06 16:37:37.911588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a03d5026d0d'
down_revision = '8e1840b6cee8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('is_reported', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'is_reported')
    # ### end Alembic commands ###
